version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update && \
            apk add  --upgrade --no-cache \
              curl \
              jq  
      - run:
          name: Build ai-critter-cam Docker image
          command: |
            docker build  -t jodfie/ai-critter-cam:${CIRCLE_BRANCH} ./camera-app
            docker build  -t jodfie/ai-critter-cam:${CIRCLE_SHA1} ./camera-app
      - run:
          name: Build ai-critter-web Docker image
          command: |
            docker build  -t jodfie/ai-critter-web:${CIRCLE_BRANCH} ./webapp/
            docker build  -t jodfie/ai-critter-web:${CIRCLE_SHA1} ./webapp/
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "jodfie/ai-critter-web:${CIRCLE_BRANCH}"
            docker push "jodfie/ai-critter-web:${CIRCLE_SHA1}"
            docker push "jodfie/ai-critter-cam:${CIRCLE_BRANCH}"
            docker push "jodfie/ai-critter-cam:${CIRCLE_SHA1}"
