version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: Setup buildx and qemu
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static
            sudo apt-get install -y binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-aarch64-static --version
            update-binfmts --version 
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx create --name arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - setup
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update && \
            apt inatall -y \
              curl \
              jq  
      - run:
          name: Build ai-critter-cam Docker image
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6  -t jodfie/ai-critter-cam:${CIRCLE_BRANCH} --push ./camera-app
      - run:
          name: Build ai-critter-web Docker image
          command: |
            DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform linux/arm64  linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 -t jodfie/ai-critter-cam:${CIRCLE_BRANCH} --push ./camera-app
